# Generated by Django 5.1.6 on 2025-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaPrices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='unit',
            field=models.CharField(default='dkk', max_length=30),
            preserve_default=False,
        ),
    ]
